server:
  port: 315


logging:
  level:
    root: INFO
    com.example: DEBUG


spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQLDialect
        properties:
          hibernate:
            default_lazy_loadable: true
        temp:
          use_jdbc_metadata_defaults: false


  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/314
    username: root
    password: mysql33!
    initialize: true

